input_data_path: "Electric_Production.csv"

preprocessing:
  log_diff: true              # Применять логарифмическую разницу

model:
  model_type: "AR"            # Тип модели
  max_lag: 75                 # Максимальное число лагов для перебора
  distribution: "gaussian"    # Распределение ошибок: gaussian / student / ...
  lag_selection_criterion: "AIC"  # Критерий выбора лага: AIC / AICc / BIC / HQC

forecast:
  forecast_steps: 20          # Кол-во шагов прогноза вперёд
  confidence: 0.95            # Уровень доверительного интервала

images_dir: "../images"       # Путь для сохранения графиков

logging:
  level: "INFO"               # Уровень логирования (DEBUG, INFO, WARNING, ERROR)
  save_logs: true             # Сохранять ли логи в файл

random_seed: 42               # Фиксируем случайное зерно для воспроизводимости (если нужно)

